spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/icpc_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:dbMigration

jwt:
  secret: THIS_IS_A_VERY_LONG_SECRET_KEY_MINIMUM_32_CHARS
  access-expiration: 900000
  refresh-expiration: 604800000