CREATE TABLE "users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "codeforces_handle" varchar(256) UNIQUE,
    "username" varchar(256),
    "email" varchar(256) UNIQUE,
    "password" varchar(256),
    "role" varchar(256),
    "rate" bigint,
    "trainee_team_id" bigint,
    "created_at" timestamp
);

CREATE TABLE "problems" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "problem_index" varchar(256),
    "problem_name" varchar(256) UNIQUE,
    "contest_id" bigint,
    "rating" int
);

CREATE TABLE "tags" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tag_name" varchar(256) UNIQUE
);

CREATE TABLE "problem_tags" (
    "problem_id" bigint,
    "tag_id" bigint,
    PRIMARY KEY ("problem_id", "tag_id")
);

CREATE TABLE "submissions" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" bigint,
    "problem_id" bigint,
    "verdict" varchar(256),
    "time_consumed_ms" int,
    "memory_consumed_bytes" int,
    "created_at" timestamp
);

CREATE TABLE "teams" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "team_code" varchar(256) UNIQUE,
    "team_name" varchar(256),
    "coach_id" bigint
);

CREATE TABLE "team_messages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sender_id" bigint,
    "team_id" bigint,
    "content" varchar(256),
    "created_at" timestamp
);

CREATE TABLE "announcements" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sender_id" bigint not null,
    "type" varchar(256) not null,
    "content" varchar(256) not null,
    "created_at" timestamp not null,
    "status" varchar(256) not null
);

CREATE TABLE "announcement_users" (
    "announcement_id" bigint not null,
    "user_id" bigint not null,
    PRIMARY KEY (announcement_id, user_id)
);

CREATE TABLE "announcement_teams" (
    "announcement_id" bigint not null,
    "team_id" bigint not null,
    PRIMARY KEY (announcement_id, team_id)
);



CREATE TABLE "notifications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" bigint,
    "title" varchar(256),
    "message" text,
    "type" varchar(256),
    "is_read" boolean,
    "created_at" timestamp,
    "updated_at" timestamp
);


create table "refresh_tokens" (
     "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     "user_id" bigint null,
     "hased_refresh_token" varchar(256) not null ,
     "created_at" timestamp not null,
     "expired_at" timestamp not null,
     "revoked" boolean not null
);

ALTER table "refresh_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "problem_tags" ADD FOREIGN KEY ("problem_id") REFERENCES "problems" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "problem_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submissions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "submissions" ADD FOREIGN KEY ("problem_id") REFERENCES "problems" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "team_messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "team_messages" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "announcements" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "announcement_users" ADD FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "announcement_users" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "announcement_teams" ADD FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "announcement_teams" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "teams" ADD FOREIGN KEY ("coach_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("trainee_team_id") REFERENCES "teams" ("id") DEFERRABLE INITIALLY IMMEDIATE;
