CREATE TABLE "reports"(
     "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     "user_id" bigint NOT NULL,
     "number_of_problems" bigint NOT NULL,
     "number_of_hints" bigint NOT NULL,
     "comment" varchar(255),
     "created_at" timestamp NOT NULL
);

ALTER TABLE "reports" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
