DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'announcments'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'announcements'
    ) THEN
        ALTER TABLE "announcments" RENAME TO "announcements";
    END IF;
END $$;

ALTER TABLE "announcements"
    ADD COLUMN IF NOT EXISTS "status" varchar(256);

CREATE TABLE IF NOT EXISTS "announcement_users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "announcement_id" bigint,
    "user_id" bigint
);

CREATE TABLE IF NOT EXISTS "announcement_teams" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "announcement_id" bigint,
    "team_id" bigint
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'announcements'
          AND column_name = 'receiver_id'
    ) THEN
        INSERT INTO "announcement_users" ("announcement_id", "user_id")
        SELECT "id", "receiver_id"
        FROM "announcements"
        WHERE "receiver_id" IS NOT NULL;
    END IF;
END $$;

ALTER TABLE "announcements"
    DROP COLUMN IF EXISTS "receiver_id" CASCADE,
    DROP COLUMN IF EXISTS "receiver_type" CASCADE,
    DROP COLUMN IF EXISTS "is_read" CASCADE;

UPDATE "announcements"
SET "status" = 'ACTIVE'
WHERE "status" IS NULL;

ALTER TABLE "announcements"
    ALTER COLUMN "sender_id" SET NOT NULL,
    ALTER COLUMN "type" SET NOT NULL,
    ALTER COLUMN "content" SET NOT NULL,
    ALTER COLUMN "created_at" SET NOT NULL,
    ALTER COLUMN "status" SET NOT NULL;

ALTER TABLE "announcement_users"
    ALTER COLUMN "announcement_id" SET NOT NULL,
    ALTER COLUMN "user_id" SET NOT NULL;

ALTER TABLE "announcement_teams"
    ALTER COLUMN "announcement_id" SET NOT NULL,
    ALTER COLUMN "team_id" SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'announcement_users'
          AND constraint_name = 'fk_announcement_users_announcement'
    ) THEN
        ALTER TABLE "announcement_users"
            ADD CONSTRAINT "fk_announcement_users_announcement"
            FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") DEFERRABLE INITIALLY IMMEDIATE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'announcement_users'
          AND constraint_name = 'fk_announcement_users_user'
    ) THEN
        ALTER TABLE "announcement_users"
            ADD CONSTRAINT "fk_announcement_users_user"
            FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'announcement_users'
          AND constraint_name = 'uk_announcement_users_announcement_user'
    ) THEN
        ALTER TABLE "announcement_users"
            ADD CONSTRAINT "uk_announcement_users_announcement_user"
            UNIQUE ("announcement_id", "user_id");
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'announcement_teams'
          AND constraint_name = 'fk_announcement_teams_announcement'
    ) THEN
        ALTER TABLE "announcement_teams"
            ADD CONSTRAINT "fk_announcement_teams_announcement"
            FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") DEFERRABLE INITIALLY IMMEDIATE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'announcement_teams'
          AND constraint_name = 'fk_announcement_teams_team'
    ) THEN
        ALTER TABLE "announcement_teams"
            ADD CONSTRAINT "fk_announcement_teams_team"
            FOREIGN KEY ("team_id") REFERENCES "teams" ("id") DEFERRABLE INITIALLY IMMEDIATE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'announcement_teams'
          AND constraint_name = 'uk_announcement_teams_announcement_team'
    ) THEN
        ALTER TABLE "announcement_teams"
            ADD CONSTRAINT "uk_announcement_teams_announcement_team"
            UNIQUE ("announcement_id", "team_id");
    END IF;
END $$;
