create table "materials"(
    id bigint primary key generated by default as identity,
    kind varchar(255),
    title varchar(255),
    subtitle varchar(255),
    size varchar(255),
    created_at timestamp,
    team_id bigint,
    url varchar(255)
);
 alter table "materials" add foreign key ("team_id") references "teams" ("id") deferrable initially immediate;