# Use Node 20 as base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# The source code will be mounted as a volume in docker-compose.yml
# Start the Vite development server and expose it
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
