package com.TrainingTracker.TraingingTracker.DataAccessLayer.Entites;

public enum NotificationType {
    TRAINEE_ASSIGNMENT_SUBMISSION,
    TRAINEE_ASSIGNMENT_SUBMISSION_REVIEW_REQUESTED,
    TRAINEE_ASSIGNMENT_SUBMISSION_REVIEW_REJECTED,
    TRAINEE_ASSIGNMENT_SUBMISSION_REVIEW_ACCEPTED,
}
